sudo: required
dist: trusty
#env:
#  global:
#  - GH_REF: github.com/szarnyasg/code-to-png.git
#  - secure:
branches:
  only:
    - master
script:
- sudo apt-get update -qq
- sudo apt-get install -qq -y texlive-base texlive-latex-extra
- sudo apt-get install -qq -y python-pygments
- sudo apt-get install -qq -y imagemagick
- make
